name: Deploy to EC2

on:
  push:
    branches: [master] # Change to 'master' if your repo uses master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/MavsMart/mavsmart-backend  # Ensure correct path
            git pull origin master  # Change to master if needed

            # Install dependencies (choose only one: npm or pip)
            if [ -f package.json ]; then
              npm install --production
            fi

            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi

            # Ensure PM2 is installed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            # Restart application
            pm2 restart app || pm2 start app.js --name "app"
