name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - master # Runs when code is pushed to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.EC2_PATH }}
            git reset --hard origin/master  # Ensure it's up to date with master branch
            git pull origin master  # Pull latest changes
            npm install --production  # Install production dependencies
            pm2 restart all  # Restart all PM2 processes to reflect changes
          EOF
