name: Deploy to EC2

on:
  push:
    branches: [master]  # Deploy when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /path/to/your/app
            git pull origin main
            # Install dependencies if needed
            npm install --production  # or `pip install -r requirements.txt`
            # Restart your app
            pm2 restart app          # or `sudo systemctl restart your-service`
